import React from 'react';

const InitialCarData = () => {
    const carData = [
        {
            id: 1,
            make: 'Toyota',
            model: 'Camry',
            year: 2022,
            color: 'Silver',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 2,
            make: 'Honda',
            model: 'Civic',
            year: 2021,
            color: 'Blue',
            transmission: 'Manual',
            status: 'available',
        },
        {
            id: 3,
            make: 'Ford',
            model: 'F-150',
            year: 2023,
            color: 'Black',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 4,
            make: 'Chevrolet',
            model: 'Silverado',
            year: 2022,
            color: 'Red',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 5,
            make: 'Jeep',
            model: 'Wrangler',
            year: 2024,
            color: 'Green',
            transmission: 'Manual',
            status: 'available',
        },
        {
            id: 6,
            make: 'Nissan',
            model: 'Altima',
            year: 2021,
            color: 'Gray',
            transmission: 'CVT',
            status: 'available',
        },
        {
            id: 7,
            make: 'Hyundai',
            model: 'Sonata',
            year: 2022,
            color: 'White',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 8,
            make: 'Kia',
            model: 'Telluride',
            year: 2023,
            color: 'Silver',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 9,
            make: 'Subaru',
            model: 'Outback',
            year: 2022,
            color: 'Blue',
            transmission: 'CVT',
            status: 'available',
        },
        {
            id: 10,
            make: 'Volkswagen',
            model: 'Jetta',
            year: 2021,
            color: 'Black',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 11,
            make: 'BMW',
            model: '3 Series',
            year: 2023,
            color: 'Silver',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 12,
            make: 'Audi',
            model: 'A4',
            year: 2022,
            color: 'White',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 13,
            make: 'Mercedes-Benz',
            model: 'C-Class',
            year: 2021,
            color: 'Black',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 14,
            make: 'Tesla',
            model: 'Model 3',
            year: 2024,
            color: 'White',
            transmission: 'Electric',
            status: 'available',
        },
        {
            id: 15,
            make: 'Toyota',
            model: 'Corolla',
            year: 2022,
            color: 'Red',
            transmission: 'Automatic',
            status: 'available',
        },
        {
            id: 16,
            make: 'Honda',
            model: 'CR-V',
            year: 2021,
            color: 'Blue',
            transmission: 'Automatic',
        },
    ];

  return carData;
};

export default InitialCarData;
